-- 收缩ScmisTAO数据库的日志  支持sql server2008 sql Server2012
USE [master]
GO
ALTER DATABASE ScmisTAO SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE ScmisTAO SET RECOVERY SIMPLE   --简单模式
GO
USE ScmisTAO
GO
DBCC SHRINKFILE (N'ScmisTAO_log', 16, TRUNCATEONLY) --检查日志文件的名字是否正确
GO
USE [master]
GO

ALTER DATABASE ScmisTAO SET RECOVERY FULL WITH NO_WAIT

GO

ALTER DATABASE ScmisTAO SET RECOVERY FULL  --还原为完全模式

GO